mode:
  development: true
database:
  dns: "root:123456@tcp(127.0.0.1:8976)/lbygin?charset=utf8mb4&parseTime=True&loc=Local"
  maxOpenConns: 100
  maxIdleConns: 100
  connMaxLifetime: 60
redis:
  url: "localhost:6379"
  password: ""
  DB: 0
jwt:
  tokenExpire: 60 # token失效时常
  signKey: "lby" # token签名使用的key
server:
  port: "8888"
app:
  name: "lby_go_app"
  version: "1.0.0"
  description: "lby创建的go——app"
log:
  maxSize: 1 # 单个日志文件最大容量，单位：MB
  maxBackups: 10 # 旧文件保留的最大个数
  maxAge: 30 # 旧文件保留的最大天数
